name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettify_code:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code javascript
        uses: creyD/prettier_action@v4.3
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
            
      - name: Run black formatter
        uses: psf/black@stable
        with:
          jupyter: true
          options: ""
        # uses: rickstaa/action-black@v1.3.3
        # with:
        #   black_args: "."
          
      - name: Reformat SQL Files
        uses: credfeto/action-sql-format@v1.4.1
            

      - name: Clang-format lint (C)
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          inplace: True

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "Code formatting"
          
  update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate README.md
        run: |
          # Start creating README.md
          echo "# Algorithms Archive" > README.md
          echo "" >> README.md
          echo "This project contains the following subfolders (up to 3 levels deep):" >> README.md
          echo "" >> README.md
          
          # Add the table headers
          echo "| Platform   | Difficulty | Problem Name |" >> README.md
          echo "|------------|------------|--------------|" >> README.md


          # Recursively find directories up to depth 3 and generate links
          find . -type d -not -path './.*' -mindepth 3 -maxdepth 3 | while read folder; do
            # Extract platform, difficulty, and problem name from the folder path
            folder_path=$(echo "$folder" | sed 's|^\./||')
            platform=$(echo "$folder_path" | cut -d'/' -f1)
            difficulty=$(echo "$folder_path" | cut -d'/' -f2)
            problem_name=$(basename "$folder")

            # Add a row to the table in README.md
            echo "| ${platform} | ${difficulty} | [${problem_name}](./${folder_path}/)|" >> README.md
          done

          echo "" >> README.md
          echo "Click on the problem names to view their contents." >> README.md

      - name: Commit and Push README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with subfolder links (adjusted depth +1 and details for depth 1)"
          git push

