name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettify_code:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code javascript
        uses: creyD/prettier_action@v4.3
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
            
      - name: Run black formatter
        uses: psf/black@stable
        # uses: rickstaa/action-black@v1.3.3
        # with:
        #   black_args: "."
          
      - name: Reformat SQL Files
        uses: credfeto/action-sql-format@v1.4.1
            

      - name: Clang-format lint (C)
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          inplace: True

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "Code formatting"
