name: Format Code

on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Python, Java, C, C++, SQL, and JavaScript dependencies
        run: |
          sudo apt-get -y install clang-format
          pip install black
          wget https://github.com/google/google-java-format/releases/download/google-java-format-1.12.0/google-java-format-1.12.0-all-deps.jar
          npm install --global prettier

      - name: Format Python Code
        run: black .

      - name: Format C and C++ Code
        run: |
          find . -name "*.c" -o -name "*.cpp" | xargs clang-format -i

      - name: Format Java Code
        run: java -jar google-java-format-1.12.0-all-deps.jar --replace **/*.java

      - name: Format JavaScript Code
        run: prettier --write "**/*.js"

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Automated code formatting after commit" || true
          git push
