name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format_and_update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prettify Code
        run: |
          npm install prettier -g
          prettier --write .

      - name: Google Java Format
        run: |
          curl -LJO https://github.com/google/google-java-format/releases/download/v1.16.0/google-java-format-1.16.0-all-deps.jar
          find . -name "*.java" | xargs java -jar google-java-format-1.16.0-all-deps.jar --replace

      - name: Run Black Formatter
        run: |
          pip install black
          black --line-length 88 --include '\.ipynb$|\.py$' .

      - name: Reformat SQL Files
        run: |
          pip install sqlparse
          find . -name '*.sql' -exec sh -c 'sqlformat -r --reindent --keywords upper {} > {}.tmp && mv {}.tmp {}' \;

      - name: Clang-format Lint (C/C++)
        run: |
          sudo apt-get install -y clang-format
          find . -name "*.[ch]" -o -name "*.cpp" -o -name "*.cc" -exec clang-format -i {} +

      - name: Generate README.md
        run: |
          echo "# Algorithms Archive" > README.md
          echo "" >> README.md
          echo "This project contains the following subfolders (up to 3 levels deep):" >> README.md
          echo "" >> README.md
          echo "| Platform   | Difficulty | Problem Name | Languages | Last Commit Date |" >> README.md
          echo "|------------|------------|--------------|-----------|------------------|" >> README.md
      
          find . -type d -not -path './.*' -mindepth 3 -maxdepth 3 | while read -r folder; do
            folder_path=${folder#./}
            platform=$(echo "$folder_path" | cut -d'/' -f1)
            difficulty=$(echo "$folder_path" | cut -d'/' -f2)
            problem_name=$(basename "$folder")
            last_commit_date=$(git log -1 --format=%cs -- "$folder")
      
            languages=$(find "$folder" -type f -name '*.*' | awk -F. '{print $NF}' | sort | uniq | while read -r ext; do
              case "$ext" in
                c) echo "C" ;;
                h) echo "C Header" ;;
                java) echo "Java" ;;
                py) echo "Python" ;;
                sql) echo "SQL" ;;
                cpp | cc) echo "C++" ;;
                js) echo "JavaScript" ;;
                *) echo "Unknown" ;;
              esac
            done | paste -sd "," -)
      
            [ -z "$languages" ] && languages="Unknown"
      
            echo "| ${platform} | ${difficulty} | [${problem_name}](./${folder_path}/) | ${languages} | ${last_commit_date} |" >> README.md
          done
      
          echo "" >> README.md
          echo "Click on the problem names to view their contents." >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (git add . && git commit -m "Code formatting and README update" && git push)
