on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest
      
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v3  
        
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:         
          node-version: 16
          
      - name: Install formatters
        run: |          
          sudo apt-get -y install clang-format
          pip install black
          wget https://github.com/google/google-java-format/releases/download/v1.7.0/google-java-format-1.17.0-all-deps.jar 
          npm install --global prettier
      
      - name: Format Python code
        run: black . --check
        
      - name: Format C/C++ code        
        run: clang-format -i -style=file *.cpp *.h    
        
      - name: Format Java code    
        run: java -jar google-java-format-1.17.0-all-deps.jar --replace '**/*.java'    
     
      - name: Format JavaScript code
        run: prettier --check '**.js'    
        
      - name: Commit changes   
        run: | 
          git config --local user.email "actions@github.com"  
          git config --local user.name "GitHub Actions"
          git commit -am "Automated code formatting"
          git push
