name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettify_code:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code javascript
        uses: creyD/prettier_action@v4.3
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
            
      - name: Run black formatter
        uses: psf/black@stable
        with:
          jupyter: true
          options: ""
        # uses: rickstaa/action-black@v1.3.3
        # with:
        #   black_args: "."
          
      - name: Reformat SQL Files
        uses: credfeto/action-sql-format@v1.4.1
            

      - name: Clang-format lint (C)
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          inplace: True

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "Code formatting"
          
  update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate README.md
        run: |
          # Start creating README.md
          echo "# Project Name" > README.md
          echo "" >> README.md
          echo "This project contains the following subfolders:" >> README.md
          echo "" >> README.md

          # Initialize a variable to track whether we are inside a <details> tag
          inside_details=false

          # Recursively find directories up to depth 3 and generate links
          find . -type d -not -path './.*' -mindepth 1 -maxdepth 3 | while read folder; do
            # Strip the leading './' from the folder name
            folder_path=$(echo "$folder" | sed 's|^\./||')
            folder_name=$(basename "$folder")
            
            # Calculate the actual depth and then add 1 to it
            actual_depth=$(echo "$folder_path" | grep -o "/" | wc -l)
            adjusted_depth=$((actual_depth + 1))
            
            # Create indentation based on the adjusted depth
            indent=$(printf '  %.0s' $(seq 1 $adjusted_depth))

            # If adjusted depth is 1, start a <details> block
            if [ $adjusted_depth -eq 1 ]; then
              if [ "$inside_details" = true ]; then
                # Close previous <details> block if open
                echo "</details>" >> README.md
              fi
              # Start new <details> block
              echo "<details>" >> README.md
              echo "<summary>${folder_name}</summary>" >> README.md
              inside_details=true
            fi

            # Add folder link to the README.md
            echo "${indent}* [${folder_name}](./${folder_path}/)" >> README.md
          done

          # Close the final <details> block if it was opened
          if [ "$inside_details" = true ]; then
            echo "</details>" >> README.md
          fi

          echo "" >> README.md
          echo "Click on each folder to view its contents." >> README.md

      - name: Commit and Push README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with subfolder links (adjusted depth +1 and details for depth 1)"
          git push

